compiler:
    solc:
        remappings:
            - "@openzeppelin=/home/markma/node_modules/@openzeppelin/"
            - "hardhat=/home/markma/node_modules/hardhat"
            - "erc721a=/home/markma/node_modules/erc721a"
